# Python Primer
* Python is a general purpose programming language, popular for its ease of use and wide range of libraries.
* Major use cases:
    * Scripting: Read/write files, control submission of jobs
    * Prototyping: Can quickly test 
    * High level interface

## Getting Started

* Anaconda:
    * Free distribution of Python, available on cluster
    * Variety of useful packages:
        * Numpy (math with arrays)
        * Scipy (advanced linear algebra/calculus/optimization functions)
        * Sympy (symbolic math operations)
        * Pandas (dataframes for organizing various data types)
        * Matplotlib (plotting)
* Pycharm:
    * Free Python GUI, useful editor functions (syntax highlighting, smart refactoring, debugger)
    * Git integration
* Juptyer Notebook:
    * Online environment combining formatted text and code
    * Good for making tutorials, lab reports, documentation
        

## Basics

* Python is dynamically typed, don't need to manually allocate memory

In [3]:
x="apple" #Need to do `str x=3` in static language
print(x)
x=3 #Can change the type of a variable, would give error in other languages
print(x)

apple
3


* If a particular type is needed, can easily convert

In [7]:
print(float(x))
print(str(x))
print(bool(x))

3.0
3
True


* The type of a variable can affect how it behaves when operated on

In [11]:
print(x/2) #integer division converts to float (in Python3.x)
print(x//2) #truncates and remains int

print(2*x) 
print(2*"dog") #string multiplication repeats the string

1.5
1
6
dogdog


## Data Structures in Python
* Hugely important for writing clear and efficient code
* Key examples
    * Lists [var,...]
    * Dicts {name : var,...}
    * Sets {var,...}
    * Tuples tuple(var,...)
    * Arrays numpy.array(var,...) (requires numpy)

### Creating Lists Pythonically
* Take the even numbers from an existing list and square them

In [2]:
B=[10,2,3,7,5,2,1]
print("standard way")
C=[]
for i in range(len(B)):
    if B[i]%2==0:  #Comparison, returns true if equal
        C.append(B[i]**2)
print(C)
        
print("Python way")
C=[b**2 for b in B if b%2==0] #list comprehension
print(C)    

standard way
[100, 4, 4]
Python way
[100, 4, 4]


* Create the multiplication table from 0 to 4 (using a list of lists)

In [22]:
print("standard way")
A=[]
for i in range(5): #iterate from 0 to 4
    temp=[]
    for j in range(5):
        temp.append(i*j)
    A.append(temp)    
print(A)

print("Python way")
table=[[i*j for j in range(5)] for i in range(5)] #nested list comprehension
print(table)

standard way
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8], [0, 3, 6, 9, 12], [0, 4, 8, 12, 16]]
Python way
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8], [0, 3, 6, 9, 12], [0, 4, 8, 12, 16]]


### Using Lists Pythonically
* Different parts of a list can be accessed conveniently by *indexing* and *slicing*

In [24]:
A=[i for i in range(10)]
print(A)
print(A[0]) #First element
print(A[-1]) #Last element
print(A[3:6]) #Slice containing A[3],A[4],A[5]
print(A[2:]) #Slice from A[2] through last element
print(A[::2],A[1::2]) #Even and odd indices
print(A[::-1]) #Reversed list

print()
#Similar for multidimensional lists, basically lists of lists
print(table[-1][2]) #Column 2 of last row (element 2 of last list)
print(table[:][1]) #Every element of column 1 (element 1 of each sublist)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0
9
[3, 4, 5]
[2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8] [1, 3, 5, 7, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

8
[0, 1, 2, 3, 4]


* Convenient builtins for modifying and searching within list

In [6]:
B=A[:] #deep copy of list
B.remove(2) #If found, remove one occurrence of this value
print(B)
print(A) #Doesn't change original list, B=A would have

del B[2] #Delete second element from list
print(B)

B.insert(1,100) #Place value at specific position
print(B)

C=B[:2]+A[2:] #Create new combined list
print(C)

print(1 in C) #Checks if value in list

[0, 1, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 5, 6, 7, 8, 9]
[0, 100, 1, 4, 5, 6, 7, 8, 9]
[0, 100, 2, 3, 4, 5, 6, 7, 8, 9]
False


* Can pack/unpack elements from a list

In [10]:
A=[1,2,3,4]
a,b,c,d=A #assign each element to a variable
print(c)

a,*b,c=A #packs everything but first and last into b
print(b)

A[1],A[2]=A[2],A[1] #quickly swap elements in list
print(A)

3
[2, 3]
[1, 3, 2, 4]


# Other builtin collections

List are probably the best general starting point, but there are better collections to work with for specialized cases.

## Tuples

* Similar to list, but fixed length and fixed values
    * Can access indices/slices and unpack values, but can't change/remove/add values
* Useful for storing related values that you won't change during runtime
    * Not required to be the same type
* Functions returning multiple variables return them as a tuple

In [7]:
T=(1,2,3)
a,b,c=T
print(b)
#T[1]=4 #Should give TypeError

O=("Origin",1.00,7)
print(O)

C=("Coordinate Axes",[1,0,0],[0,1,0],[0,0,1]) #Can store multable variables
#C[1]=14 #Will give TypeError
C[1][:]=[1,2,3] #Changing contents of the variable, not the variable itself
print(C)


2
('Origin', 1.0, 7)
('Coordinate Axes', [1, 2, 3], [0, 1, 0], [0, 0, 1])


## Sets

* Mathematical sets, can change in size, but only saves unique, immutable elements


In [15]:
S1={i for i in range(5)}
S2={i for i in range(0,10,2)}
print("S1="+str(S1))
print("S2="+str(S2))

S1.add(5) #Add an element
print(S1|S2) #Union/or
print(S1^S2) #Exclusive or
print(S1&S2) #Intersection/and
print(S1-S2) #Set difference (remove elements of 2nd set from 1st)
print(S1>=S2) #Is S1 a superset of S2?

#S2.add([1,2,3]) #Type error, lists are mutable
S2.add((1,2,3)) #Tuples are immutable, works
print(S2)

S1={0, 1, 2, 3, 4}
S2={0, 2, 4, 6, 8}
{0, 1, 2, 3, 4, 5, 6, 8}
{1, 3, 5, 6, 8}
{0, 2, 4}
{1, 3, 5}
False
{0, 2, 4, 6, 8, (1, 2, 3)}


## Dictionaries

* Like a list, but stores both keys and values. Keys are immutable, values can be mutable. 
* Since Python 3.7, stored in the order added. Earlier versions didn't maintain order.

In [18]:
A={"first":1,"second":2,"third":3}
print(A)

fruits=["apple","orange","banana"]
prices=[3.00,2.50,4.25]
groceries={k:v for k,v in zip(fruits,prices)} #dict comprehension
print(groceries)

{'first': 1, 'second': 2, 'third': 3}
{'apple': 3.0, 'orange': 2.5, 'banana': 4.25}


* Differences compared to list due to the need to access keys/values together or separately

In [21]:
print(list(groceries.keys()))
print(list(groceries.values()))

#print(groceries["grape"]) #Gives KeyError
print(groceries.get("grape",0)) #Returns value if present or default if not
groceries["grape"]=.25
groceries.setdefault("grape",1400) #Adds only if not already present
print(groceries)

big={**A,**groceries} #Unpack to combine two dicts
print(big)


['apple', 'orange', 'banana']
[3.0, 2.5, 4.25]
0
{'apple': 3.0, 'orange': 2.5, 'banana': 4.25, 'grape': 0.25}
{'first': 1, 'second': 2, 'third': 3, 'apple': 3.0, 'orange': 2.5, 'banana': 4.25, 'grape': 0.25}


# Numpy arrays
* Fixed size, variable elements. Designed for ease of performing mathematical operations
* Not builtin to Python, must be downloaded separately or included with Anaconda

## Making arrays
* A few different methods, depending on how simple a structure you are working with

In [36]:
import numpy as np
print("A")
A=np.array([1,7,9]) #By hand, usually only for small arrays with no discernible pattern
print(A)

print("\nB")
B=np.arange(25) #Simple patterns
print(B)
print(B.shape)
newB=np.reshape(B,(5,5)) #Turns into 5 by 5 array
print(newB.T) #can also do np.transpose(newB)
print(newB.shape)

print("\nC")
C=np.array([j**2 if j%2==0 else 13 for j in range(10)]) #More complicated patterns
print(C)

print("\nD")
D=np.zeros((3,3)) #Array of zeros, good for when you know the shape, but little else
print(D)

print("\nE")
E=np.eye(3) #Identity matrix
E*=3 #Elementwise multiplication
print(E)

print("\nF")
F=np.fromfile("array.txt",sep=" ") #large dataset, already formatted
print(F)

A
[1 7 9]

B
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
(5, 5)

C
[ 0 13  4 13 16 13 36 13 64 13]

D
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

E
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]

F
[ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.]


## Using Arrays
* Most commonly just trying to line combine a large set of numbers

In [33]:
print("Operations by element")
print((C * F)**2) #Multiply element by element, then square each
v=np.arange(5)
print(newB*v) #Broadcasting along columns
v=v.reshape((5,1)) 
print(newB*v) #Broadcasting along rows

print("\nMatrix/vector operations")
print(np.dot(C,F)) #Dot product
outer=np.outer(C,F)
print(outer) #Outer product
print(newB@v) #Matrix multiplication, np.multiply(newB,v) before Python3.5

Operations by element
[0.000000e+00 1.690000e+02 6.400000e+01 1.521000e+03 6.400000e+03
 1.081600e+04 2.190240e+05 7.452900e+04 4.734976e+06 5.112250e+05]
[[ 0  1  4  9 16]
 [ 0  6 14 24 36]
 [ 0 11 24 39 56]
 [ 0 16 34 54 76]
 [ 0 21 44 69 96]]
[[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [20 22 24 26 28]
 [45 48 51 54 57]
 [80 84 88 92 96]]

Matrix/vector operations
3876.0
[[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [  13.   13.   26.   39.   65.  104.  169.  273.  442.  715.]
 [   4.    4.    8.   12.   20.   32.   52.   84.  136.  220.]
 [  13.   13.   26.   39.   65.  104.  169.  273.  442.  715.]
 [  16.   16.   32.   48.   80.  128.  208.  336.  544.  880.]
 [  13.   13.   26.   39.   65.  104.  169.  273.  442.  715.]
 [  36.   36.   72.  108.  180.  288.  468.  756. 1224. 1980.]
 [  13.   13.   26.   39.   65.  104.  169.  273.  442.  715.]
 [  64.   64.  128.  192.  320.  512.  832. 1344. 2176. 3520.]
 [  13.   13.   26.   39.   65.  104.  169.  273.  442.  715.]]

* Some additional indexing/postprocessing that is unique to arrays

In [34]:
print("Remove less than 50")
newOut=np.copy(outer)
newOut[np.abs(newOut)<50]=0 #Index by a boolean condition
print(newOut)

print("Keep lower triangle")
mask=np.tri(10,dtype=bool) #Matrix of True in lower triangle, False in upper
print(outer[mask]) #Extract lower triangle into 1D array
outer*=mask #All indices where mask is False to zero 
print(outer)

Remove less than 50
[[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.   65.  104.  169.  273.  442.  715.]
 [   0.    0.    0.    0.    0.    0.   52.   84.  136.  220.]
 [   0.    0.    0.    0.   65.  104.  169.  273.  442.  715.]
 [   0.    0.    0.    0.   80.  128.  208.  336.  544.  880.]
 [   0.    0.    0.    0.   65.  104.  169.  273.  442.  715.]
 [   0.    0.   72.  108.  180.  288.  468.  756. 1224. 1980.]
 [   0.    0.    0.    0.   65.  104.  169.  273.  442.  715.]
 [  64.   64.  128.  192.  320.  512.  832. 1344. 2176. 3520.]
 [   0.    0.    0.    0.   65.  104.  169.  273.  442.  715.]]
Keep lower triangle
[   0.   13.   13.    4.    4.    8.   13.   13.   26.   39.   16.   16.
   32.   48.   80.   13.   13.   26.   39.   65.  104.   36.   36.   72.
  108.  180.  288.  468.   13.   13.   26.   39.   65.  104.  169.  273.
   64.   64.  128.  192.  320.  512.  832. 1344. 2176.   13.   13.   26.
   39.   65.  104.  169.  273.  442. 